### ISSUE TITLE
アカウント設定画面で認証に成功した場合は成功メッセージを表示して数秒後に画面を自動で閉じたい

### ISSUE THREAD

**Issue by ryoma-yama** [ryoma-yama/lab-gantt#10]
- [ ] ✔ Sucesss! みたいなメッセージをエラーメッセージの表示箇所に出す

**Comment by tkg-reis** [comment]
@ryoma-yama 
お疲れ様です。
確認ですが
`数秒後に画面を自動で閉じたい `の部分について
どんなイメージもたれてますか？

**Comment by ryoma-yama** [comment]
@tkg-reis 

順序で言うとこんな感じですね
- ユーザー情報取得成功
- 成功メッセージ表示
- setTimeOutとかで3秒後に現在ウィンドウを閉じるのに使ってる関数を実行

って感じです。閉じる事自体の動作にはそのまま今ある関数使ってもらうイメージです😀

**Comment by tkg-reis** [comment]
@ryoma-yama 
やってみます！
