### ISSUE TITLE
レスポンシブ対応

### ISSUE THREAD

**Issue by taiga-hirose** [ryoma-yama/lab-gantt#45]
ヘッダー部分のレスポンシブ対応を行なってください。
スマホサイズの場合以下の表示内容のみを表示し、非表示内容をハンバーガーメニューに格納してください。

◼︎表示内容
アイコン
Group
PRJ

◼︎非表示内容
タイトル
プロファイル
設定

**Comment by ryoma-yama** [comment]
Closed with #50, #51
